/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '6/16/16 3:39 PM' with Gradle 2.13
 *
 * @author ltudor, @date 6/16/16 3:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
